SELECT A.UNOP_CD_UNID_OPER as UN, 'URUCU' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS, 
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"
              
FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D      

WHERE  A.POCO_CD_PREFIXO    = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO       = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF     = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF         = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM       = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO      = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER  =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER  =  D.UNOP_CD_UNID_OPER
  AND  A.FLUI_CD_FLUIDO    IN ('OLEO','COND')
  AND  A.TIOP_CD_TIPO_OPER  = 'P'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER  = 169

GROUP BY  A.UNOP_CD_UNID_OPER,  D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'CEARA MAR' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE,  to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D       

WHERE A.POCO_CD_PREFIXO     = B.POCO_CD_PREFIXO 
  AND A.POCO_NR_POCO        = B.POCO_NR_POCO    
  AND A.POCO_CD_REPERF      = B.POCO_CD_REPERF  
  AND A.POCO_SG_UF          = B.POCO_SG_UF
  AND A.POCO_CD_SUBM        = B.POCO_CD_SUBM    
  AND B.CAMP_SG_CAMPO       = D.CAMP_SG_CAMPO
  AND A.UNOP_CD_UNID_OPER   =  B.UNOP_CD_UNID_OPER
  AND B.UNOP_CD_UNID_OPER   =  D.UNOP_CD_UNID_OPER
  AND A.FLUI_CD_FLUIDO     IN ('OLEO','COND')
  AND A.TIOP_CD_TIPO_OPER   = 'P'
  AND B.AMBI_CD_AMBIENTE    = 'M'  
  AND A.POCO_SG_UF          = 'CE'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND A.UNOP_CD_UNID_OPER   =  161
  
GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'RGN MISTURA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS COFD_QA_FL_REALIZA

 FROM  COLUNA_FLUIDO_MES A, POCO B, CAMPO D

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO 
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER
  AND  B.CAMP_SG_CAMPO NOT IN ('AT','CR','EP','XA','FZB','IC','PE','DEN','ARB')
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  A.TIOP_CD_TIPO_OPER  = 'P'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER  =  161

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'PESCADA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

 FROM  COLUNA_FLUIDO_MES A, POCO B, CAMPO D, ATIVO E

WHERE  A.POCO_CD_PREFIXO     = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO        = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF      = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF          = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM        = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO       = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER   = B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER   = D.UNOP_CD_UNID_OPER
  AND  E.UNOP_CD_UNID_OPER   = A.UNOP_CD_UNID_OPER
  AND  D.ATIV_CD_ATIVO       = E.ATIV_CD_ATIVO
  AND  B.CAMP_SG_CAMPO      IN ('PE','DEN','ARB')
  AND  A.FLUI_CD_FLUIDO     IN ('OLEO','COND')
  AND  A.TIOP_CD_TIPO_OPER   = 'P'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  E.UNOP_CD_UNID_OPER   = 161

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')
     
UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN,  'FAZENDA BELEM' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE,  to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D             

WHERE  A.POCO_CD_PREFIXO     = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO        = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF      = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF          = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM        = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO       = D.CAMP_SG_CAMPO 
  AND  A.UNOP_CD_UNID_OPER   =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER   =  D.UNOP_CD_UNID_OPER 
  AND  B.CAMP_SG_CAMPO      IN ('FZB','IC')
  AND  A.FLUI_CD_FLUIDO     IN ('OLEO','COND')
  AND  A.TIOP_CD_TIPO_OPER   = 'P'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER   =  161

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')
      
UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'ALAGOANO' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D             

WHERE  A.POCO_CD_PREFIXO     = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO        = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF      = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF          = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM        = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO       = D.CAMP_SG_CAMPO 
  AND  A.UNOP_CD_UNID_OPER   =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER   =  D.UNOP_CD_UNID_OPER
  AND  B.CAMP_SG_CAMPO      IN ('ANB', 'CSM', 'JAU','FU','PIR','SMC')
  AND  A.FLUI_CD_FLUIDO     IN ('OLEO','COND')
  AND  A.TIOP_CD_TIPO_OPER   = 'P'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER   =  120

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')
     
UNION ALL   

SELECT A.UNOP_CD_UNID_OPER AS UN, 'PIRANEMA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D             

WHERE  A.POCO_CD_PREFIXO     = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO        = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF      = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF          = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM        = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO       = D.CAMP_SG_CAMPO 
  AND  A.UNOP_CD_UNID_OPER   =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER   =  D.UNOP_CD_UNID_OPER
  AND  B.CAMP_SG_CAMPO       = 'PRM'
  AND  A.FLUI_CD_FLUIDO     IN ('OLEO','COND')
  AND  A.TIOP_CD_TIPO_OPER   = 'P'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER   =  120

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')
     
UNION ALL   
         
SELECT A.UNOP_CD_UNID_OPER AS UN,  'SERGIPANO MAR' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE,  to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D             

WHERE  A.POCO_CD_PREFIXO     = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO        = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF      = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF          = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM        = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO       = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER   =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER   =  D.UNOP_CD_UNID_OPER 
  AND  B.CAMP_SG_CAMPO      IN ('ATS','CB','CM','DO','GA','PARU','TTI')
  /*ATS apesar de ambiente=T produção escoa pelo mar*/
  AND  A.FLUI_CD_FLUIDO     IN ('OLEO','COND')
  AND  A.TIOP_CD_TIPO_OPER   = 'P'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER   =  120

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'SERGIPANO TERRA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D             

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
       AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
       AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
       AND  A.POCO_SG_UF      = B.POCO_SG_UF
       AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
       AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO   
       AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
       AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER
       AND  B.CAMP_SG_CAMPO IN ('AG','AN','ARI','BRG','CL','CP','IP','MG','RO','SZ','SG')
       /*SG apesar de ambiente=M produção escoa por terra*/
       AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
       AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
       AND  A.UNOP_CD_UNID_OPER =  120

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'BAIANO MISTURA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"
              
FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D      

WHERE  A.POCO_CD_PREFIXO    = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO       = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF     = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF         = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM       = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO      = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER  =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER  =  D.UNOP_CD_UNID_OPER
  AND  A.FLUI_CD_FLUIDO    IN ('OLEO','COND')
  AND  A.TIOP_CD_TIPO_OPER  = 'P'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 110

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')
 
UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'ESPÍRITO SANTO' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D           

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER
  AND  B.CAMP_SG_CAMPO <> 'JUB'
  AND  B.CAMP_SG_CAMPO <> 'GLF'
  AND  B.CAMP_SG_CAMPO <> 'FAL'
  AND  B.CAMP_SG_CAMPO <> 'PER'
  AND  B.CAMP_SG_CAMPO <> 'CHT'
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 162

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'JUBARTE' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D                

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER
  AND B.CAMP_SG_CAMPO IN ('JUB','CHT')
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 162

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'GOLFINHO' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  B.CAMP_SG_CAMPO = 'GLF'
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 162

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'PEROA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  B.CAMP_SG_CAMPO = 'PER'
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 162

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'FAZENDA ALEGRE' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  B.CAMP_SG_CAMPO = 'FAL'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 162

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'MARLIM' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  B.CAMP_SG_CAMPO IN ('MRL','VD')
  AND  A.TIOP_CD_TIPO_OPER  = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'MARLIM LESTE' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  B.CAMP_SG_CAMPO      = 'MLL'
  AND  A.TIOP_CD_TIPO_OPER  = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'MARLIM SUL' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  B.CAMP_SG_CAMPO = 'MLS'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'ALBACORA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  B.CAMP_SG_CAMPO = 'AB'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'ALBACORA LESTE' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  B.CAMP_SG_CAMPO = 'ABL'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'BARRACUDA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  B.CAMP_SG_CAMPO = 'BR'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'CARATINGA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  B.CAMP_SG_CAMPO = 'CRT'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'ESPADARTE' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  B.CAMP_SG_CAMPO = 'ESP'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'RONCADOR' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  B.CAMP_SG_CAMPO = 'RO'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'CABIÚNAS MISTURA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  B.CAMP_SG_CAMPO IN ('ANQ','BG','BI','BO','CG','CH','CO','CRP','EN','ENO','GP','GPN','LI','MA','MLH','MO','NA','NEN','PA','PG','PM','PU','TR','VL','VM')
  AND  A.TIOP_CD_TIPO_OPER  = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'BADEJO' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, POCO B, CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  B.CAMP_SG_CAMPO = 'BD'
  AND  A.TIOP_CD_TIPO_OPER  = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  A.COFM_DT_REFERENCIA = to_date('2008.02.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 160

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'CORAL' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"

FROM   COLUNA_FLUIDO_MES A, e004.POCO B, e004.CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  B.CAMP_SG_CAMPO = 'CRL'
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 113

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')

UNION ALL

SELECT A.UNOP_CD_UNID_OPER AS UN, 'CONDENSADO DE MERLUZA' AS CORRENTE, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm') AS MÊS,
       round(SUM(A.COFM_QA_FL_REALIZA),2) AS "VOLUME (M³)"
       
FROM   COLUNA_FLUIDO_MES A, e004.POCO B, e004.CAMPO D               

WHERE  A.POCO_CD_PREFIXO = B.POCO_CD_PREFIXO 
  AND  A.POCO_NR_POCO    = B.POCO_NR_POCO    
  AND  A.POCO_CD_REPERF  = B.POCO_CD_REPERF  
  AND  A.POCO_SG_UF      = B.POCO_SG_UF
  AND  A.POCO_CD_SUBM    = B.POCO_CD_SUBM    
  AND  B.CAMP_SG_CAMPO   = D.CAMP_SG_CAMPO  
  AND  A.UNOP_CD_UNID_OPER =  B.UNOP_CD_UNID_OPER
  AND  B.UNOP_CD_UNID_OPER =  D.UNOP_CD_UNID_OPER 
  AND  A.TIOP_CD_TIPO_OPER    = 'P'
  AND  A.FLUI_CD_FLUIDO IN ('OLEO','COND')
  AND  D.CAMP_SG_CAMPO = 'MLZ'
  AND  A.COFM_DT_REFERENCIA = to_date('2008.01.01','yyyy.mm.dd')
  AND  A.UNOP_CD_UNID_OPER = 113

GROUP BY  A.UNOP_CD_UNID_OPER, D.CAMP_NM_CAMPO, B.AMBI_CD_AMBIENTE, to_char(A.COFM_DT_REFERENCIA,'yyyy.mm')


