SELECT 
	CPA.CPEA_NM_CONTROLE_PERFIL,
	UO.UNOP_SG_UNID_OPER,
	UPA.USER_CD_USUARIO
FROM 
	CPROD.CONTROLE_PERFIL_ACESSO CPA,
	CPROD.USUARIO_PERFIL_ACESSO UPA,
	CPROD.VW_UNID_OPERATIVA UO
WHERE
	CPA.CPEA_SQ_CONTROLE_PERFIL = UPA.CPEA_SQ_CONTROLE_PERFIL AND
	UO.UNOP_CD_UNID_OPER(+) = UPA.UNOP_CD_UNID_OPER AND
	CPA.CPEA_SQ_CONTROLE_PERFIL IN (24, 25) -- busca COORDENADOR e EDITOR local
ORDER BY
	CPA.CPEA_NM_CONTROLE_PERFIL,
	UO.IPUO_NR_ORDENACAO_GEOGRAFICA,
	UPA.USER_CD_USUARIO;
